name: splitwrld
version: '${version}'
main: de.groupxyz.splitwrld.Splitwrld
api-version: '1.20'
author: GroupXyz
commands:
  listworlds:
    description: List all worlds
  pingworldserver:
    description: Ping worldserver
  worldserverconfigreload:
    description: Reload config
