# config.yml

# For a list of enchantments see: https://jd.bukkit.org/org/bukkit/enchantments/Enchantment.html

# Note: chance feature might not be working yet, please leave at 100 or use custom loot tables

#prefix
serverPrefix: "[&e&k1&r&eTreasure&3Hunt&k1&r] "

#loot
loot:
  sword:
    material: DIAMOND_SWORD
    enchantments:
      DAMAGE_ALL: 5
      LOOT_BONUS_MOBS: 3
      MENDING: 1
    slot: 0
    chance: 100
    name: "&cTreasurehunter's &dSword"
    lore:
      - '&6Mighty Sword'
      - '&6of a brave'
      - '&6adventurer.'
  bow:
    material: BOW
    enchantments:
      ARROW_DAMAGE: 3
      ARROW_FIRE: 1
      ARROW_INFINITE: 1
      MENDING: 1
    slot: 5
    chance: 100
    name: "&cTreasurehunter's &dBow"
    lore:
      - '&6Mighty Bow'
      - '&6of a brave'
      - '&6adventurer.'
  chestplate:
    material: DIAMOND_CHESTPLATE
    slot: 2
    chance: 100
  diamonds:
    material: DIAMOND
    amount: 5
    slot: 8
    chance: 100
  emeralds:
    material: EMERALD
    amount: 3
    slot: 4
    chance: 5
  iron_ingots:
    material: IRON_INGOT
    amount: 10
    slot: 18
    chance: 100

#optional loot tables
useLootTables: false
lootTables:
  simple_dungeon:
    name: "minecraft:chests/simple_dungeon"
    active: true
  abandoned_mineshaft:
    name: "minecraft:chests/abandoned_mineshaft"
    active: true
  end_city_treasure:
    name: "minecraft:chests/end_city_treasure"
    active: false
