# config.yml

#prefix
serverPrefix: "[&e&k1&r&eTreasure&3Hunt&k1&r] "

#loot
loot:
  sword:
    material: DIAMOND_SWORD
    enchantments:
      DAMAGE_ALL: 5
      LOOT_BONUS_MOBS: 3
      MENDING: 1
    slot: 0
    name: "&cTreasurehunter's &dSword"
    lore:
      - '&6Mighty Sword'
      - '&6of a brave'
      - '&6adventurer.'
  bow:
    material: BOW
    enchantments:
      ARROW_DAMAGE: 3
      ARROW_FIRE: 1
      ARROW_INFINITE: 1
      MENDING: 1
    slot: 5
    name: "&cTreasurehunter's &dBow"
    lore:
      - '&6Mighty Bow'
      - '&6of a brave'
      - '&6adventurer.'
  chestplate:
    material: DIAMOND_CHESTPLATE
    slot: 2
  diamonds:
    material: DIAMOND
    amount: 5
    slot: 8
  emeralds:
    material: EMERALD
    amount: 3
    slot: 4
  iron_ingots:
    material: IRON_INGOT
    amount: 10
    slot: 18
