name: treasurehunt
version: '${version}'
main: de.groupxyz.treasurehunt.Treasurehunt
api-version: '1.20'
author: GroupXyz
description: Treasurehunt plugin initially created by GroupXyz for the german smp zickzacknetwork.de
commands:
  treasurehunt:
    description: Start a treasurehunt-event
    usage: /treasurehunt
    permission: treasurehunt.op
  treasurehuntdebug:
    description: Show location of the treasure!
    usage: /treasurehuntdebug
    permission: treasurehunt.op
  treasurehuntreload:
    description: Reload config
    usage: /treasurehuntreload
    permission: treasurehunt.op
  treasurehuntcustom:
    description: Start a treasurehunt with a custom location
    permission: treasurehunt.op
  treasurehuntversion:
    description: Show the version of treasurehunt
  treasurehuntrange:
    description: Set the range in which the treasure should be generated
    permission: treasurehunt.op
  treasurehuntlanguage:
    description: Change the language of the treasurehunt plugin
    permission: treasurehunt.op
