name: treasurehunt
version: '${version}'
main: de.groupxyz.treasurehunt.Treasurehunt
api-version: '1.20'
author: GroupXyz
description: Treasurehunt Plugin initially created for the smp ZickZackNetwork.de
commands:
  treasurehunt:
    description: Start a Treasurehunt-Event
    usage: /treasurehunt
    permission: treasurehunt.op
  treasurehuntdebug:
    description: Show location of the Treasure!
    usage: /treasurehuntdebug
    permission: treasurehunt.op
