name: starryban
version: '${version}'
main: de.groupxyz.starryban.Starryban
api-version: '1.20'
author: GroupXyz
commands:
  mute:
    description: Mute a Player.
    permission: starry.mute
  unmute:
    description: Unmute a Player.
    permission: starry.unmute
  ban:
    description: Ban a Player.
    permission: starry.ban
  unban:
    description: Unban a Player.
    permission: starry.unban
