name: tpworld
version: '${version}'
main: de.groupxyz.tpworld.Tpworld
author: GroupXyz
website: Contact me in Discord - groupxyz
api-version: '1.20'
commands:
  tpworld:
    description: Teleport to a specified world.
    usage: /tpworld [worldname]
    permission: tpw.op
  worldcustom:
    description: Import a custom World
    usage: /worldcustom
    permission: tpw.op