# CSCraft2 Config

game:
  countdown: 30

  min_players: 2

  max_players: 10

  ct_spawn:
    world: world
    x: 0.0
    y: 64.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0

  t_spawn:
    world: world
    x: 0.0
    y: 64.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0