name: nopluginspy
version: '${version}'
main: de.groupxyz.nopluginspy.Nopluginspy
api-version: '1.20'
author: Groupxyz
commands:
  nopluginspy:
    description: Reaload the Config of nopluginspy!
    usage: /nopluginspy reload
    permission: nps.reload
