minPlayers: 4
oldWorldDeletionEnabled: false
language: "de"
spawnPoints:
  - world: stonehenge
    x: 100
    y: 65
    z: 200
    pitch: 0
    yaw: 0
  - world: aquamarine
    x: 150
    y: 65
    z: 250
    pitch: 0
    yaw: 0
luckyBlocks:
  - world: "stonehenge"
    x: 100
    y: 64
    z: 100
  - world: "aquamarine"
    x: 102
    y: 64
    z: 105
lootTable: "minecraft:chests/end_city_treasure"
isDebug: false
